name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install uv
      run: |
        pip install uv

    - name: Create uv venv, install deps, run tests and type checks
      run: |
        uv venv .venv
        source .venv/bin/activate
        uv pip install .[dev]
        pytest
